# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

complexity:
  LongMethod:
    active: true
    threshold: 69
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']

formatting:
  Indentation:
    active: false
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 2

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: true
    values: []

empty-blocks:
  active: false
