# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
